print("Enter the name:")
name=input()
print("Enter the creator name:")
creator=input()
print("Enter the purpose:")
purpose=input()
print("Enter the memory size:")
memory=input()
print("Enter the speed:")
speed=input()
print("My Details:")
print(f"I am {name} , created by {creator}, for the purpose of {purpose}.\nMemory I consume is around {memory} and my speed is {speed}.")